apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-te
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: kubernetes-te
  template:
    metadata:
      labels:
        app: kubernetes-te
    spec:
      containers:
      - name: kubernetes-te
        image: kubernetes-te:latest
        imagePullPolicy: Never  # Tell Kubernetes not to pull from a registry
        # image: somg0703/kubernetes-te:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-te
spec:
  selector:
    app: kubernetes-te
  ports:
  - port: 8080
    targetPort: 5000